# Generated by Django 5.0.3 on 2024-03-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='main_content',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
