# Generated by Django 5.0.3 on 2024-03-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codelisting',
            name='link',
            field=models.URLField(default=2024),
            preserve_default=False,
        ),
    ]
