# Generated by Django 5.0.3 on 2024-03-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_codelisting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelisting',
            name='image',
            field=models.ImageField(null=True, upload_to='code_listings/'),
        ),
    ]
